= Pflichtenheft Turnierverwaltung
Jakob Ratzenböck, Adrian Moser, Silvio Kalinke
1.0.1, 2020-04-20
:sourcedir: ../src/main/java
:icons: font
:toc: left

== 1. CLD

[plantuml,CLD,png]
----
@startuml
class Tournament {
  id: int
  name: String
  pointsWin: int
  pointsDraw: int
  groupSize: int

}
class Match {
  id: int
  team1: Team
  team2: Team
  description: String
}
class Team {
  id: int
  tournament: Tournament
}
class Phase{
  id: int
  order: int
  tournament: Tournament
}

Match <-- Team
Match <-- Team
Phase <-- Match
Tournament <-- Phase
Tournament <-- Team : Anmeldung
@enduml
----

Phase ... Gruppenphase, k.o.-Runde, Achtel-, Viertel-, Halbfinale

=== Beispiel

==== Struktur

* Turnier: Fussballturnier Schulschluss 2020
* Phasen:
** Gruppenphase -> Order=1
** Viertelfinale -> Order=2
** Halbfinale -> Order=3
** Finale-> Order=4
* Teams
** 3ahitm
** 1afel
** 3ahif

==== Ablauf

. Erstellen eines Turniers
. Teams melden sich zu einem Turnier (zB Webseite)
. Abhängig von der Anzahl werden Turnierphasen erstellt.
. Auslosung der Teams in Phasen
. Eintragen der Spielergebnisse
. Aufstieg in die nächste Runde (Turnierphase)
. Eintragen der Spielergebnisse
. ...

==== Programmierablauf

. Zuerst Tabellen mit SQL-CREATE erstellen
. Dann die Teams mit INSERT einfügen
. Dann die Java-Repositories für die Tabellen erstellen.
. Dann mit Unit-Tests das Turnier simulieren.
. Wenn die Business Logik in Java funktioniert, wird erst mit JavaFX begonnen.

== 2. Ausgangssituation
Um ein Turnier so einfach wie möglich zu veranstalten/organisieren wird ein Verwaltungssystem dafür entwickelt.

vgl https://github.com/htl-leonding/2016_TuV3r


== 3. Istzustand
Im Moment sind nur Interessenten bekannt die noch nicht fix eingeschrieben/angemeldet sind.

Es soll ein Programm entwickelt werden, mit welchem man Turniere mittels einer Benutzerfreundlichen grafischen Oberfläche Turniere erstellen bzw. verwalten kann.


== 4. Problemstellung
Für eine leichtere und angenehmere Verwaltung von Turnieren soll ein Programm erstellt werden, wo sich die Teilnehmer selbst eintragen können, die an dem Turnier interessiert sind.


== 5. Aufgabenstellung
=== 5.1 Funktionale Anforderungen

[plantuml,wireframe,png]
----
@startsalt
{
Name         | "                 "
Modifiers:   | { (X) public | () default | () private | () protected
	            [] abstract | [] final   | [] static }
Superclass:  | { "java.lang.Object " | [Browse...] }
}
@endsalt
----
=== 5.2 Nichtfunktionale Anforderungen (NFA)


== 6. Zielsetzung


== 7. Mengengerüst
=== Rahmenbedingungen
zB Vorgaben vom Auftraggeber


== 8. Projekthandbuch "Organisatorische Rahmenbedingungen"

=== GANTT-Diagramm

mit User-Stories (definiert in YouTrack)

[plantuml,gantt-protoype,png]
----
@startuml
[Test prototype] lasts 10 days
[Prototype completed] happens at [Test prototype]'s end
[Setup assembly line] lasts 12 days
[Setup assembly line] starts at [Test prototype]'s end
[Test prototype 2] lasts 3 days
[Test prototype 2] starts at [Prototype completed]'s end
@enduml
----


link:demo.html[Demo]

