= Pflichtenheft Turnierverwaltung
Jakob Ratzenböck, Adrian Moser, Silvio Kalinke
1.0.1, 2020-04-20
:sourcedir: ../src/main/java
:icons: font
:toc: left

== 1. CLD


== 2. Ausgangssituation
Um ein Turnier so einfach wie möglich zu veranstalten/organisieren wird ein Verwaltungssystem dafür entwickelt.



== 3. Istzustand
Im Moment sind nur Interessenten bekannt die noch nicht fix eingeschrieben/angemeldet sind.

Es soll ein Programm entwickelt werden, mit welchem man Turniere mittels einer Benutzerfreundlichen grafischen Oberfläche Turniere erstellen bzw. verwalten kann.


== 4. Problemstellung
Für eine leichtere und angenehmere Verwaltung von Turnieren soll ein Programm erstellt werden, wo sich die Teilnehmer selbst eintragen können, die an dem Turnier interessiert sind.


== 5. Aufgabenstellung
=== 5.1 Funktionale Anforderungen

[plantuml,wireframe,png]
----
@startsalt
{
Name         | "                 "
Modifiers:   | { (X) public | () default | () private | () protected
	            [] abstract | [] final   | [] static }
Superclass:  | { "java.lang.Object " | [Browse...] }
}
@endsalt
----
=== 5.2 Nichtfunktionale Anforderungen (NFA)


== 6. Zielsetzng


== 7. Mengengerüst
=== Rahmenbedingungen
zB Vorgaben vom Auftraggeber


== 8. Projekthandbuch "Organisatorische Rahmenbedingungen"

=== GANTT-Diagramm

mit User-Stories (definiert in YouTrack)

[plantuml,gantt-protoype,png]
----
@startuml
[Test prototype] lasts 10 days
[Prototype completed] happens at [Test prototype]'s end
[Setup assembly line] lasts 12 days
[Setup assembly line] starts at [Test prototype]'s end
[Test prototype 2] lasts 3 days
[Test prototype 2] starts at [Prototype completed]'s end
@enduml
----


link:demo.html[Demo]

